apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-service
  description: A demo Node.js Express website created with Backstage Software Templates
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: user:guest
  lifecycle: experimental

